name: "Concurrency Test"
on:
  push:
    branches: [main]
concurrency:
  group: Build-${{ github.ref }}
  cancel-in-progress: true

jobs:
   build-and-test-on-pr:
     name: build and test on pull request
     runs-on: ubuntu-latest
     steps:
       - name: Build the code
         run: |
           echo "starting code build"
           sleep 1m
           echo "Finished code build"
           
       - name: Test the code
         run: |
           echo "starting code build"
           sleep 1m
           echo "Finished code build"
           echo ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
