name: "Calling another repo workflow file"
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  release:
    types: [edited,published]

# jobs:
#   notifications:
#     uses: suniljamadar/action-testing/.github/workflows/test.yml@main
